import Link from 'next/link';
import {notFound} from 'next/navigation';
import {blends,books,prompts,readPieces} from '@/lib/content';
const valid=['read','write','featured-writer','books','prompts','nook','membership','about','coffee','login'];

export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;if(!valid.includes(slug))notFound();

if(slug==='featured-writer') return <>
<section className="featuredHero"><div className="featuredShade"></div><div className="featuredPortrait"></div><div className="featuredIntro"><small>FEATURED WRITER</small><h1>Maya Rowe</h1><p>Poet. Essayist. Observer of small miracles.</p><blockquote>“I write to make sense of the quiet<br/>things that insist on being seen.”</blockquote><Link className="goldBtn" href="#work">Explore Maya’s Work</Link></div><div className="chalkReading">NEXT READING<br/><b>Maya Rowe</b><br/><strong>May 29 · 7PM</strong><span>Tickets at<br/>the Counter</span></div></section>
<section className="featuredGrid" id="work">
 <article className="paperCell essayCell"><small>FEATURED ESSAY</small><h2>The Map We Carry</h2><p>Some maps are handed down. Others we draw in the margins. This is about what we inherit, what we change, and what we choose to carry forward.</p><Link href="#">Read the Essay →</Link><div className="botanical">⌇</div></article>
 <article className="greenCell"><small>UPCOMING READING</small><p>▣ &nbsp; Thursday, May 29, 7PM</p><p>◷ &nbsp; Ink Spot Literary Coffeehouse</p><p>⌖ &nbsp; In our café + livestream</p><button>Reserve Your Seat →</button><span>Books will be available for signing.</span></article>
 <article className="paperCell interviewCell"><small>WRITER INTERVIEW</small><blockquote>“Hope is a practice.<br/>So is paying attention.”</blockquote><p>In conversation on writing, community, and the small acts that change us.</p><Link href="#">Read the Interview →</Link></article>
 <article className="paperCell picksCell"><small>SHELF PICKS</small>{[['The Orchard of Falling Light','A Novel by L. Calder'],['Salt on the Wind','Poems by J. Maris'],['Museum of Borrowed Days','Stories by T. Nguyen']].map(([t,s],i)=><div className="pick" key={t}><i className={'bookCover bc'+i}></i><span><b>{t}</b><small>{s}</small></span></div>)}<Link href="/books">See All Picks →</Link></article>
 <article className="blendWide"><div><small>MAYA'S HOUSE BLEND</small><h2>Quiet Cartographer</h2><p>Notes of toasted hazelnut, dark cocoa, and soft light.</p><Link href="/coffee">Meet the Blend →</Link></div><div className="blendStill"><div className="bagArt"><b>INK<br/>SPOT</b><small>Quiet<br/>Cartographer</small></div><div className="cupArt"></div></div></article>
 <article className="burgundyCell"><small>ABOUT MAYA</small><p>Maya Rowe is the author of the poetry collection <em>Fruit of the Almost</em> and the essay collection <em>Listen for the Neighboring Sea.</em> Her work appears in <em>The Common, North American Review,</em> and elsewhere.</p><span>mayarowe.com →</span></article>
 <article className="blueCell"><small>ON THE TABLE</small><p>Inspired by this month’s writer.<br/>These titles are sparking conversation in the café.</p><div className="threeBooks"><i></i><i></i><i></i></div><Link href="/books">Browse the Table →</Link></article>
</section></>;

if(slug==='nook') return <>
<section className="nookHero"><div className="nookCopy"><h1>The Nook</h1><em>A community of writers.<br/>Real places. Real windows.</em><p>Share a corner of your world.<br/>Inspire someone else.</p><button>▣ &nbsp; Share Your Nook</button><Link href="#nooks">How it works →</Link></div><div className="corkboard"><div className="pol p1"></div><div className="pol p2"></div><div className="pol p3"></div><div className="pol p4"></div><div className="note">There is no<br/>better nook<br/>than the one<br/>that’s yours.</div><div className="note dark">Show us where<br/>the words<br/>find you.</div><div className="featuredPol"><div></div><b>FEATURED NOOK</b><p>Morning light, strong coffee,<br/>and a long list of dreams.</p><small>@wordsbyanna · Portland, OR</small></div></div><div className="nookShelf"><b>COMMUNITY<br/>CREATES<br/>CURIOSITY.</b></div></section>
<section className="nookBrowse" id="nooks"><div className="filters">{['All Nooks','Windows & Light','Café Corners','Books & Shelves','Desks & Studios','Outdoors','On the Road','Typewriters','Mornings'].map((x,i)=><button className={i===0?'selected':''} key={x}>{x}</button>)}<span>Sort by&nbsp;&nbsp;<button>Most Recent⌄</button></span></div><div className="nookGallery">{[
 ['Rainy day views and unfinished drafts.','@elizabeth.ink','Seattle, WA'],['Old typewriter, new ideas.','@jameswrites','Austin, TX'],['Corner booth, loud café, quiet mind.','@notebook_nomad','Chicago, IL'],['Where the day begins and the words follow.','@lattesandlines','Portland, OR'],['Sunlight, plants, and a page that listens.','@greeninkling','Savannah, GA'],['Inherited desk. Borrowed time. My kind of perfect.','@inkherstories','Philadelphia, PA'],['Books, candles, and one stubborn paragraph.','@marginnotes','Boston, MA'],['A little chaos helps.','@draftandcoffee','Nashville, TN'],['Porch table. One notebook.','@slowpages','Athens, GA'],['The old window seat.','@quietdrafts','Madison, WI'],['Typewriter weather.','@smallhours','Denver, CO'],['Where the first sentence finally happened.','@paperhabit','Brooklyn, NY']].map((n,i)=><article className={i===3?'featuredCard':''} key={i}><div className={'nookPhoto np'+(i%6)}></div><p>{n[0]}</p><small>{n[1]}<br/>{n[2]}</small><span>♡ {18+i*3}</span></article>)}</div></section></>;

if(slug==='books') return <div className="inner"><div className="pageKicker">BOOKS ON THE TABLE</div><h1>Someone left these here for you.</h1><p className="pageIntro">No bestseller rank. No popularity score. A table changes because people keep leaving good things on it.</p><div className="bookTable">{books.map((b,i)=><article key={i}><div className={'fakeBook c'+i}><span>{b.title}</span></div><div><small>{b.section}</small><h2>{b.title}</h2><em>{b.author}</em><p>{b.note}</p><button>Pick it up</button></div></article>)}</div></div>;
if(slug==='prompts') return <div className="inner"><div className="pageKicker">PROMPTS</div><h1>A sentence worth ruining your afternoon for.</h1><p className="pageIntro">Sharp enough to pull a story loose. Strange enough to take you somewhere you did not plan to go.</p><div className="promptList">{prompts.map((p,i)=><article key={i}><small>{p.kicker}</small><h2>{p.text}</h2><p>{p.note}</p><button>Respond to this prompt</button></article>)}</div></div>;
if(slug==='read') return <div className="inner"><div className="pageKicker">READ</div><h1>Read what someone thought was worth putting on the table.</h1><p className="pageIntro">Curated work, arranged like a magazine rack by someone whose taste you trust.</p><div className="readList">{readPieces.map((p,i)=><article key={i}><small>{p[0]}</small><h2>{p[1]}</h2><p>by {p[2]}</p><Link href="#">Read →</Link></article>)}</div></div>;
if(slug==='write') return <div className="inner"><div className="pageKicker">WRITE</div><h1>Bring something worth reading.</h1><p className="pageIntro">Respond to a prompt, send an excerpt, propose a reading, pin your writing place, or put your name forward for the residency.</p><div className="writeGrid">{['Respond to the current prompt','Submit work','Share something short','Submit to The Nook','Propose a reading','Submit a book excerpt','Become a featured writer'].map(x=><article key={x}><h2>{x}</h2><p>Tell us what it is, why it belongs here, and give the work enough context to be read seriously.</p><button>Begin →</button></article>)}</div></div>;
if(slug==='coffee') return <div className="inner"><div className="pageKicker">COFFEE</div><h1>Coffee with something to say.</h1><p className="pageIntro">A few roasts, each tied back to the writing culture. The bag carries a prompt. The QR code brings you back to the table.</p><div className="coffeeGrid">{blends.map((b,i)=><article key={i}><div className="bagBig">INK<br/>SPOT<small>{b.name}</small></div><div><small>{b.roast}</small><h2>{b.name}</h2><p><b>{b.notes}</b></p><p>{b.line}</p><blockquote>{b.prompt}</blockquote><button>Get the roast</button></div></article>)}</div></div>;
if(slug==='membership') return <div className="inner memberPage"><div className="pageKicker">MEMBERSHIP</div><h1>Become a regular.</h1><p className="pageIntro">Membership is less about unlocking software and more about having a chair people begin to recognize.</p><div className="memberBox"><h2>The Regular</h2><p>Early featured work · member readings · coffee offers · special editions · small gatherings · first access to drops</p><button>Join Ink Spot</button></div></div>;
if(slug==='about') return <div className="inner about"><div className="pageKicker">ABOUT</div><h1>A literary coffeehouse on the internet.</h1><p>Ink Spot is a place for readers and writers to encounter good work and each other without turning every sentence into a competition for attention.</p><p>There is no infinite feed here. No follower scoreboard. No trending page deciding what you are supposed to care about. There are writers at the table, books left behind, prompts taped near the machine, coffee, readings, and the occasional thing you did not know you were looking for.</p><h2>Great stories start here.</h2></div>;
return <div className="inner"><div className="pageKicker">LOG IN</div><h1>Welcome back.</h1><div className="loginBox"><label>Email<input type="email" placeholder="you@example.com"/></label><button>Continue</button></div></div>}
