import Link from 'next/link';
import {notFound} from 'next/navigation';
import {featuredWriter, blends, books, prompts, nook, readPieces} from '@/lib/content';
const valid=['read','write','featured-writer','books','prompts','nook','membership','about','coffee','login'];
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;if(!valid.includes(slug))notFound();
if(slug==='featured-writer') return <div className="inner"><div className="pageKicker">FEATURED WRITER</div><h1>{featuredWriter.name}</h1><p className="pageIntro">One writer. One table. Stay awhile.</p><div className="featureGrid"><section><h2>Read</h2><h3>{featuredWriter.work.title}</h3><p>{featuredWriter.work.dek}</p><button>Read the featured work</button></section><section id="listen"><h2>Listen</h2><p>{featuredWriter.audio}</p><div className="audio">▶ <span>Audio reading</span><i>12:08</i></div></section><section id="conversation"><h2>Conversation</h2><p>{featuredWriter.interview}</p><button>Read the conversation</button></section><section><h2>On Their Shelf</h2>{featuredWriter.books.map(x=><p key={x}>↳ {x}</p>)}</section><section className="darkPanel"><h2>Their Blend</h2><h3>{featuredWriter.blend}</h3><p>{blends[0].notes}</p><Link href="/coffee">Pour another →</Link></section></div></div>;
if(slug==='books') return <div className="inner"><div className="pageKicker">BOOKS ON THE TABLE</div><h1>Someone left these here for you.</h1><p className="pageIntro">No bestseller rank. No popularity score. A table changes because people keep leaving good things on it.</p><div className="bookTable">{books.map((b,i)=><article key={i}><div className={'fakeBook c'+i}><span>{b.title}</span></div><div><small>{b.section}</small><h2>{b.title}</h2><em>{b.author}</em><p>{b.note}</p><button>Pick it up</button></div></article>)}</div></div>;
if(slug==='prompts') return <div className="inner"><div className="pageKicker">PROMPTS</div><h1>A sentence worth ruining your afternoon for.</h1><p className="pageIntro">Sharp enough to pull a story loose. Strange enough to take you somewhere you did not plan to go.</p><div className="promptList">{prompts.map((p,i)=><article key={i}><small>{p.kicker}</small><h2>{p.text}</h2><p>{p.note}</p><button>Respond to this prompt</button></article>)}</div></div>;
if(slug==='nook') return <div className="inner cork"><div className="pageKicker">THE NOOK</div><h1>Where the work gets written.</h1><p className="pageIntro">Real places. Bad lighting welcome.</p><div className="nookWall">{nook.map((n,i)=><article key={i} style={{transform:`rotate(${[-2,3,-1,2,-3,1][i]}deg)`}}><div className={'snap s'+i}></div><b>{n.place}</b><p>{n.note}</p></article>)}</div><button>Pin your writing place</button></div>;
if(slug==='read') return <div className="inner"><div className="pageKicker">READ</div><h1>Read what someone thought was worth putting on the table.</h1><p className="pageIntro">Curated work, arranged like a magazine rack by someone whose taste you trust.</p><div className="readList">{readPieces.map((p,i)=><article key={i}><small>{p[0]}</small><h2>{p[1]}</h2><p>by {p[2]}</p><Link href="#">Read →</Link></article>)}</div></div>;
if(slug==='write') return <div className="inner"><div className="pageKicker">WRITE</div><h1>Bring something worth reading.</h1><p className="pageIntro">Respond to a prompt, send an excerpt, propose a reading, pin your writing place, or put your name forward for the residency.</p><div className="writeGrid">{['Respond to the current prompt','Submit work','Share something short','Submit to The Nook','Propose a reading','Submit a book excerpt','Become a featured writer'].map(x=><article key={x}><h2>{x}</h2><p>Tell us what it is, why it belongs here, and give the work enough context to be read seriously.</p><button>Begin →</button></article>)}</div></div>;
if(slug==='coffee') return <div className="inner"><div className="pageKicker">COFFEE</div><h1>Coffee with something to say.</h1><p className="pageIntro">A few roasts, each tied back to the writing culture. The bag carries a prompt. The QR code brings you back to the table.</p><div className="coffeeGrid">{blends.map((b,i)=><article key={i}><div className="bagBig">INK<br/>SPOT<small>{b.name}</small></div><div><small>{b.roast}</small><h2>{b.name}</h2><p><b>{b.notes}</b></p><p>{b.line}</p><blockquote>{b.prompt}</blockquote><button>Get the roast</button></div></article>)}</div></div>;
if(slug==='membership') return <div className="inner memberPage"><div className="pageKicker">MEMBERSHIP</div><h1>Become a regular.</h1><p className="pageIntro">Membership is less about unlocking software and more about having a chair people begin to recognize.</p><div className="memberBox"><h2>The Regular</h2><p>Early featured work · member readings · coffee offers · special editions · small gatherings · first access to drops</p><button>Join Ink Spot</button></div></div>;
if(slug==='about') return <div className="inner about"><div className="pageKicker">ABOUT</div><h1>A literary coffeehouse on the internet.</h1><p>Ink Spot is a place for readers and writers to encounter good work and each other without turning every sentence into a competition for attention.</p><p>There is no infinite feed here. No follower scoreboard. No trending page deciding what you are supposed to care about. There are writers at the table, books left behind, prompts taped near the machine, coffee, readings, and the occasional thing you did not know you were looking for.</p><h2>Great stories start here.</h2></div>;
return <div className="inner"><div className="pageKicker">LOG IN</div><h1>Welcome back.</h1><div className="loginBox"><label>Email<input type="email" placeholder="you@example.com"/></label><button>Continue</button></div></div>}
